[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes correctly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# Fallback redirects for SPA
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200 